import type { VibeAssetErrorEvent, VibeAssetLoadEvent, VibeHandle, VibeInitialState, VibeResolveResult, VibeViewerItem, VibeStatus } from '@wyxos/vibe';
import type { BrowseFormInstance } from '@/composables/useBrowseForm';
import type { LocalFileDeletion } from '@/composables/useLocalFileDeletion';
import type { TabContentContainerInteractions } from '@/composables/useTabContentContainerInteractions';
import type { TabContentItemInteractions } from '@/composables/useTabContentItemInteractions';
import type { TabContentPromptDialog as TabContentPromptDialogHandle } from '@/composables/useTabContentPromptDialog';
import type { FeedItem, TabData } from '@/composables/useTabs';
import type { ServiceOption } from '@/lib/browseCatalog';
import type { LoadedItemsBulkAction } from '@/lib/tabContentLoadedItemsBulkActions';
import type { BrowseFeedHandle } from '@/types/browse';
import type { File } from '@/types/file';
import type { ReactionType } from '@/types/reaction';
import type { LocalSourceSelection } from '@/utils/localSourceSelection';

export type FileSheetState = { isOpen: boolean };
export type FileSheetPresentation = 'inline' | 'overlay';
export type FileViewerDataShape = {
    fileData: { value: File | null };
    isLoadingFileData: { value: boolean };
    isRefreshingSourceMetadata?: { value: boolean };
    sourceMetadataRefreshError?: { value: string | null };
    setFileData: (file: File) => void;
    refreshSourceMetadata?: (fileId: number) => Promise<File | null>;
};
export type DownloadedReactionPromptShape = {
    data: { open: { value: boolean } };
    chooseReact: () => void;
    chooseRedownload: () => void;
    close: () => void;
    setOpen: (value: boolean) => void;
};
export type MouseShortcutHandlers = ReturnType<typeof import('@/lib/tabContentV2MouseShortcuts').createBrowseV2MouseShortcutHandlers>;

export type TabContentV2ViewProps = {
    activeIndex: number;
    autoScrollActive?: boolean;
    autoScrollMax?: number;
    autoScrollMin?: number;
    autoScrollSpeed?: number;
    availableServices: ServiceOption[];
    availableSources: string[];
    applyFilters: () => Promise<void>;
    applyService: () => Promise<void>;
    cancelFill: () => void;
    closeFileSheet: () => void;
    confirmBatchAction?: () => void;
    containerInteractions: TabContentContainerInteractions;
    currentVisibleItem: FeedItem | null;
    cancelBatchAction?: () => void;
    cancelRemoveLoadedItems?: () => void;
    canRemoveLoadedItems?: boolean;
    downloadedReactionPrompt: DownloadedReactionPromptShape;
    fileSheetState: FileSheetState;
    fileSheetItem: FeedItem | null;
    fileViewerData: FileViewerDataShape;
    form: BrowseFormInstance;
    fillActionsDisabled?: boolean;
    fillCallCount?: number;
    fillCallCountMax?: number;
    fillCallCountMin?: number;
    fillUntilCount?: () => void;
    fillUntilEnd?: () => void;
    goToFirstPage: () => Promise<void>;
    confirmRemoveLoadedItems?: () => void | Promise<void>;
    handleAssetErrors: (errors: VibeAssetErrorEvent[]) => void;
    handleAssetLoads: (loads: VibeAssetLoadEvent[]) => void;
    handleContainerBlacklistChange: (change: { action: 'created' | 'deleted'; blacklist: import('@/types/container-blacklist').ContainerBlacklist }) => void;
    handleItemsChange: (items: VibeViewerItem[]) => void;
    handleReaction: (item: VibeViewerItem, type: ReactionType) => void | Promise<void>;
    headerMasonry: BrowseFeedHandle | null;
    isFilterSheetOpen: boolean;
    isPreviewRegenerationQueued?: (item: FeedItem) => boolean;
    itemInteractions: TabContentItemInteractions;
    localFileDeletion: LocalFileDeletion;
    localService: ServiceOption | null | undefined;
    loadNext: () => void | Promise<void>;
    loadedItemsRemovalCount?: number;
    loadedItemsRemovalOpen?: boolean;
    masonryRenderKey: number;
    mouseShortcuts: MouseShortcutHandlers;
    openFileSheet: () => void;
    openFileSheetForItem: (item: FeedItem, index: number) => void;
    removeItemFromTab?: (item: FeedItem) => void | Promise<void>;
    removeLoadedItems?: () => void;
    removingLoadedItems?: boolean;
    pendingBatchAction?: LoadedItemsBulkAction | null;
    promptDialog: TabContentPromptDialogHandle;
    queuePreviewRegeneration?: (item: FeedItem, options?: { automatic?: boolean }) => void | Promise<void>;
    fileSheetPresentation: FileSheetPresentation;
    resolve: (params: { cursor: string | null; pageSize: number; signal?: AbortSignal }) => Promise<VibeResolveResult>;
    setAutoScrollSpeed?: (value: number) => void;
    setFillCallCount?: (value: number) => void;
    setFilterSheetOpen: (value: boolean) => void;
    setLocalMode: (value: boolean) => void;
    setVibeHandle: (value: VibeHandle | null) => void;
    isRemovingItemFromTab?: (item: FeedItem) => boolean;
    shouldShowForm: boolean;
    tab: TabData | null;
    totalAvailable: number | null;
    updateFeed: (value: 'local' | 'online') => void;
    updateSource: (value: LocalSourceSelection) => void;
    updateActiveIndex: (value: number) => void;
    updateService: (value: string) => void | Promise<void>;
    updateSurfaceMode: (value: 'fullscreen' | 'list') => void;
    surfaceMode: 'fullscreen' | 'list';
    toggleAutoScroll?: () => void;
    vibeInitialCursor: string | null;
    vibeInitialState: VibeInitialState | undefined;
    vibeStatus: VibeStatus;
    viewerKey: string;
};
