<?php

namespace App\Services\Downloads;

use App\Models\DownloadTransfer;

final class DownloadTransferRequestOptions
{
    public function __construct(private readonly DownloadTransferRuntimeStore $runtimeStore) {}

    /**
     * @return array<string, string>
     */
    public function httpHeaders(DownloadTransfer $transfer): array
    {
        $headers = [];

        if ($transfer->file?->referrer_url) {
            $headers['Referer'] = $transfer->file->referrer_url;
        }

        $runtimeContext = $this->runtimeStore->getForTransfer($transfer->id);
        $runtimeUserAgent = trim((string) ($runtimeContext['user_agent'] ?? ''));
        $runtimeCookies = trim((string) ($runtimeContext['cookies'] ?? ''));

        if ($runtimeUserAgent !== '') {
            $headers['User-Agent'] = $runtimeUserAgent;
        }

        if ($runtimeCookies !== '') {
            $headers['Cookie'] = $runtimeCookies;
        }

        return $headers;
    }

    /**
     * @return array{0: array{cookies_path?: string, user_agent?: string}, 1: string|null}
     */
    public function ytDlpRuntimeOptions(DownloadTransfer $transfer, string $absoluteTmpDir): array
    {
        $runtimeContext = $this->runtimeStore->getForTransfer($transfer->id);
        $runtimeOptions = [];
        $cookieJarPath = null;

        $runtimeUserAgent = trim((string) ($runtimeContext['user_agent'] ?? ''));
        if ($runtimeUserAgent !== '') {
            $runtimeOptions['user_agent'] = $runtimeUserAgent;
        }

        $runtimeCookies = trim((string) ($runtimeContext['cookies'] ?? ''));
        if ($runtimeCookies !== '') {
            $cookieJarPath = $this->writeCookieJar(
                $runtimeCookies,
                $this->cookieDomainForTransfer($transfer),
                $absoluteTmpDir
            );

            if ($cookieJarPath !== null) {
                $runtimeOptions['cookies_path'] = $cookieJarPath;
            }
        }

        return [$runtimeOptions, $cookieJarPath];
    }

    private function cookieDomainForTransfer(DownloadTransfer $transfer): ?string
    {
        $candidates = [
            $transfer->url,
            $transfer->file?->referrer_url,
            data_get($transfer->file?->listing_metadata, 'page_url'),
        ];

        foreach ($candidates as $candidate) {
            if (! is_string($candidate) || $candidate === '') {
                continue;
            }

            $host = parse_url($candidate, PHP_URL_HOST);
            if (is_string($host) && $host !== '') {
                return strtolower($host);
            }
        }

        return null;
    }

    private function writeCookieJar(string $cookieHeader, ?string $domain, string $absoluteTmpDir): ?string
    {
        if ($domain === null || $domain === '') {
            return null;
        }

        $cookiePairs = array_map('trim', explode(';', $cookieHeader));
        $lines = ['# Netscape HTTP Cookie File', '# Generated by Atlas runtime options'];

        foreach ($cookiePairs as $pair) {
            if ($pair === '' || ! str_contains($pair, '=')) {
                continue;
            }

            [$name, $value] = array_pad(explode('=', $pair, 2), 2, '');
            $name = trim($name);
            $value = trim($value);

            if ($name === '' || preg_match('/^[!#$%&\'*+\-.^_`|~0-9A-Za-z]+$/', $name) !== 1) {
                continue;
            }

            $value = str_replace(["\t", "\r", "\n"], '', $value);
            $lines[] = "{$domain}\tFALSE\t/\tFALSE\t0\t{$name}\t{$value}";
        }

        if (count($lines) <= 2) {
            return null;
        }

        $cookieJarPath = $absoluteTmpDir.DIRECTORY_SEPARATOR.'runtime-cookies.txt';
        $written = @file_put_contents($cookieJarPath, implode(PHP_EOL, $lines).PHP_EOL);

        return $written !== false ? $cookieJarPath : null;
    }
}
